# configuration for pre-commit git hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.6
  hooks:
    - id: ruff  # Linter
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format  # Formatter
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.8
  hooks:
    - id: uv-lock
