name: "CodeQL"

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "*.example"
      - ".gitignore"

jobs:
  analyze:
    name: Code Checks 
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre Commit Checks
        uses: pre-commit/action@v3.0.1

	  - name: Install uv
		uses: astral-sh/setup-uv@v5

	  - name: Test Build
		env:
		  UV_SYSTEM_PYTHON: 1
		run: uv build
